sudo: required
services:
  - docker

before_install:
  - docker build -t kamil/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kamil/react-test npm test

after_success:
  - docker build -t kamil/multi-client ./client
  - docker build -t kamil/multi-nginx ./nginx
  - docker build -t kamil/multi-server ./server
  - docker build -t kamil/multi-worker ./worker
  # log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images do docker hub
  - docker push kamil/multi-client
  - docker push kamil/multi-nginx
  - docker push kamil/multi-server
  - docker push kamil/multi-worker