sudo: required
services:
  - docker

before_install:
  - docker build -t kamilpietrzkiewiczcom/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kamilpietrzkiewiczcom/react-test npm test

after_success:
  - docker build -t kamilpietrzkiewiczcom/multi-client ./client
  - docker build -t kamilpietrzkiewiczcom/multi-nginx ./nginx
  - docker build -t kamilpietrzkiewiczcom/multi-server ./server
  - docker build -t kamilpietrzkiewiczcom/multi-worker ./worker
  # log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images do docker hub
  - docker push kamilpietrzkiewiczcom/multi-client
  - docker push kamilpietrzkiewiczcom/multi-nginx
  - docker push kamilpietrzkiewiczcom/multi-server
  - docker push kamilpietrzkiewiczcom/multi-worker